version: "3.8"
services:
  tomtrust-ai:
    build: .
    container_name: tomtrust-ai
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
